export type AvaliableKeys =
  | 'logData'
  | 'logInvoke'
  | 'new-window'
  | 'createContract'
  | 'updateContract'
  | 'updateDatabase'
  | 'deleteContract'
  | 'getContracts'
  | 'getOverdueContracts'
  | 'getOverdueThisWeek'
